# Generated by Django 4.0 on 2022-01-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_myuser_is_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('deactivated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor/')),
                ('speciality', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed')], default='in progress', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('appointment_schedule', models.ManyToManyField(to='hospital.AppointmentSchedule')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.myuser')),
            ],
        ),
    ]
