# Generated by Django 4.0 on 2022-01-22 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_schedule',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='startTime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 22, 7, 15, 6, 967368, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='appointment_schedule',
            field=models.ManyToManyField(to='hospital.AppointmentSchedule'),
        ),
    ]
