# Generated by Django 4.0 on 2022-01-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
