# Generated by Django 4.0 on 2022-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_appointment_appointment_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='appointment_schedule',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.AppointmentSchedule'),
        ),
    ]
