# Generated by Django 4.0 on 2022-01-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_myuser_is_hospital'),
        ('hospital', '0003_hospital_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.myuser'),
            preserve_default=False,
        ),
    ]
