# Generated by Django 4.0 on 2022-01-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_rename_appointmentschedule_doctorschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='appointment_schedule',
            new_name='doctor_schedule',
        ),
    ]
