# Generated by Django 4.0 on 2022-01-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
