# Generated by Django 4.0 on 2022-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_doctor_endtime_doctor_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
