# Generated by Django 4.0 on 2022-01-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_appointment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
