# Generated by Django 4.0 on 2022-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_appointment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='locationName',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
