# Generated by Django 4.0 on 2022-01-18 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_appointment_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
            preserve_default=False,
        ),
    ]
