# Generated by Django 4.0 on 2022-01-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
