# Generated by Django 4.0 on 2022-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_remove_payment_ispaid_remove_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payed_with',
            field=models.CharField(choices=[('razorpay', 'razorpay'), ('paypal', 'paypal')], default='paypal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
