# Generated by Django 4.0 on 2022-02-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_payment_payed_with_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='in progress', max_length=20),
        ),
    ]
