# Generated by Django 4.0 on 2022-01-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_hospital_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
