# Generated by Django 4.0 on 2022-04-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.FloatField(default=0),
        ),
    ]
