# Generated by Django 4.0 on 2022-01-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_myuser_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_verified',
            new_name='email_verified',
        ),
    ]
