# Generated by Django 4.0 on 2022-01-24 10:46

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_forgotpasswordcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='code',
            field=models.UUIDField(default=account.models.random_with_N_digits, editable=False, unique=True),
        ),
    ]
