# Generated by Django 4.0 on 2022-01-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_forgotpasswordcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='can_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
