# Generated by Django 4.0 on 2022-01-24 11:29

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_myuser_can_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordcode',
            name='code',
            field=models.CharField(default=account.models.random_with_N_digits, editable=False, max_length=20, unique=True),
        ),
    ]
